# 指定workflow的名称
name: Github Vue Demo Actions

# 触发workflow的条件
on:
  push:
    branches: ["master"]

env:
  IMAGE_NAME: vue-study:latest

# jobs
jobs:
  build_push:
    name: Docker Build Job
    runs-on: ubuntu-latest
    steps:
      # 签出代码
      - name: Checkout
        uses: actions/checkout@v2

      # 准备QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # 构建docker环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # 推送镜像到DockerHub
      - name: Push image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{secrets.DOCKERHUB_USERNAME}}/hust:vue-study
          push: true
